name: crowdsecurity/whitelists
description: "Whitelist events from my ip addresses"
whitelist:
  reason: "my ip ranges"
  ip:
    - "192.168.5.6" # Home. Jellyfin was throwing 403 forbidden errors on some clients.
    - "127.0.0.1" # Local Host
  cidr:
    - "192.168.0.0/16" # Local IPs + ZeroTier Network
    - "10.0.0.0/8" # Local IPs
    - "172.16.0.0/12" # Local/Docker IPs
    - "100.68.10.0/24" # Tailnet IPs
