########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.14.0/24
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.15.0/24

########################### SECRETS
secrets:
  basic_auth_credentials:
    file: $DOCKERDIR/secrets/basic_auth_credentials
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token
  authelia_jwt_secret:
    file: $DOCKERDIR/secrets/authelia_jwt_secret
  authelia_session_secret:
    file: $DOCKERDIR/secrets/authelia_session_secret
  authelia_storage_encryption_key:
    file: $DOCKERDIR/secrets/authelia_storage_encryption_key

########################### SERVICES
services:
  # Dozzle - Real-time Docker Log Viewer
  dozzle:
    image: amir20/dozzle:v8.13.11
    container_name: dozzle
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
#    profiles: ["apps", "all"]
    networks:
      - default
      - socket_proxy
      - t3_proxy
    ports:
      - "$DOZZLE_PORT:8080"
    environment:
      - DOZZLE_NO_ANALYTICS=1
      - DOZZLE_LEVEL=info
#      - DOZZLE_TAILSIZE=300
      - DOZZLE_FILTER="status=running"
      # - DOZZLE_FILTER="label=log_me" # limits logs displayed to containers with this label
      - DOCKER_HOST
    # volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock # Use Docker Socket Proxy instead for improved security
    labels:
      - "traefik.enable=true"

#include:
#  ########################### SERVICES
#  # HOSTNAME_HS / HOSTNAME_MS defined in .env file
#  - compose/$HOSTNAME_HS/socket-proxy.yml
#  - compose/$HOSTNAME_HS/traefik.yml
#  - compose/$HOSTNAME_HS/authelia.yml
#  - compose/$HOSTNAME_HS/crowdsec.yml
#  - compose/$HOSTNAME_HS/cloudflare-bouncer.yml
#  - compose/$HOSTNAME_HS/traefik-bouncer.yml
#  - compose/$HOSTNAME_HS/portainer.yml
#  - compose/$HOSTNAME_HS/dozzle.yml
#  - compose/$HOSTNAME_HS/docker-gc.yml
#  - compose/$HOSTNAME_HS/uptime-kuma.yml

