esphome:
  name: sonoff-s20-balls
  friendly_name: sonoff-s20-balls

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
# api:

ota:
  - platform: esphome
    password: "b3f25ed95e4e6fbe3563ceb4c3c14530"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoff-S20 Fallback Hotspot"
    password: "figGYsHiXE2B"

  manual_ip:
    static_ip: 192.168.5.13
    gateway: 192.168.5.1
    subnet: 255.255.255.0

captive_portal:

# Device Specific Config
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S20 Balls Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Sonoff S20 Balls Status"

sensor:
  - platform: wifi_signal
    name: "Sonoff S20 Balls WiFi Signal"
    update_interval: 60s

switch:
  - platform: gpio
    name: "Sonoff S20 Balls Relay"
    pin: GPIO12
    id: relay

status_led:
  pin: GPIO13

mqtt:
  broker: 192.168.5.6
  username: max
  password: blaataap
  topic_prefix: c26    