#{"source": "file", "filename": "/does/not/exist", "labels": {"type": "syslog"}}

filenames:
  - /var/log/auth.log
  - /var/log/syslog
  - /var/log/kern.log
  - /var/log/ufw.log
  - /var/log/mail.log
labels:
  type: syslog
---
filenames:
  - /logs/hs/traefik/*.log
labels:
  type: traefik
