http:
  routers:
    calibre-web-automated-rtr:
      rule: "Host(`cwa.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure-internal
        - websecure-external
      middlewares:
     #   - kobo-sync-headers
        - chain-authelia@file
   #     - calibre-logout@file
      service: calibre-web-automated-svc
      tls:
        certResolver: dns-cloudflare

#  middlewares:
    # ----------------------------------------------------
    # DEFINE THE KOBO SYNC HEADERS MIDDLEWARE HERE
    # ----------------------------------------------------
 #   kobo-sync-headers:
#      headers:
  #      customRequestHeaders:
  #        X-Scheme: "https"
    # ----------------------------------------------------

  services:
    calibre-web-automated-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.5.8:8083"

