http:
  routers:
    jellyfin-rtr:
      rule: "Host(`jellyfin.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure-internal
        - websecure-external
      middlewares:
        - chain-authelia@file
      service: jellyfin-svc
      tls:
        certResolver: dns-cloudflare
  services:
    jellyfin-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.5.7:8096"
