http:
  routers:
    syncthing-rtr:
      rule: "Host(`sync.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure-internal
        - websecure-external
      middlewares:
        - chain-authelia@file
      service: syncthing-svc
      tls:
        certResolver: dns-cloudflare
  services:
    syncthing-svc:
      loadBalancer:
        servers:
#          - url: "http://{{env "SERVER_LAN_IP"}}:9000" # Or, "http://portainer:9000" if Portainer is part of t3_proxy network
          - url: "http://192.168.5.8:8384"

