http:
  routers:
    jellyfin-bypass:
      rule: "Host(`jellyfin.{{env \"DOMAINNAME\"}}`) && (PathPrefix(`/socket`) || PathPrefix(`/web`) || PathPrefix(`/Videos`) || PathPrefix(`/emby`))"
      entryPoints:
        - websecure-external
        - websecure-internal
      service: jellyfin-svc
      tls:
        certResolver: dns-cloudflare

  routers:
    jellyfin-rtr:
      rule: "Host(`jellyfin.{{env \"DOMAINNAME\"}}`)"
      entryPoints:
        - websecure-external
        - websecure-internal
      middlewares:
        - chain-authelia@file
        - jellyfin-headers@file
      service: jellyfin-svc
      tls:
        certResolver: dns-cloudflare

  services:
    jellyfin-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.5.7:8096"

  middlewares:
    jellyfin-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Frame-Options: "SAMEORIGIN"
          X-Content-Type-Options: "nosniff"
