http:
  routers:
    sonarr-rtr:
      rule: "Host(`sonarr.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure-internal
        - websecure-external
      middlewares:
        - chain-authelia@file
      service: sonarr-svc
      tls:
        certResolver: dns-cloudflare
  services:
    sonarr-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.5.7:8989"
