http:
  routers:
    readarr-rtr:
      rule: "Host(`readarr.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure-internal
        - websecure-external
      middlewares:
        - chain-authelia@file
      service: readarr-svc
      tls:
        certResolver: dns-cloudflare
  services:
    readarr-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.5.7:8787"
