###############################################################
#                   Authelia configuration                    #
###############################################################
 
server:
  address: tcp://0.0.0.0:9091/
  buffers:
    read: 4096
    write: 4096
  endpoints:
    enable_pprof: false
    enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""
 
# https://www.authelia.com/configuration/miscellaneous/logging/
log:
  level: info
  format: text
  file_path: /config/authelia.log
  keep_stdout: true
 
# https://www.authelia.com/configuration/second-factor/time-based-one-time-password/
totp:
  issuer: kemeel.com
  period: 30
  skew: 1

# AUTHELIA_DUO_PLACEHOLDER

# https://www.authelia.com/reference/guides/passwords/
authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 256 # blocks this much of the RAM

# https://www.authelia.com/overview/authorization/access-control/
access_control:
  default_policy: deny
  rules:
    # - domain:
    #     - "*.example.com"
    #     - "example.com"
    #   policy: bypass
    #   networks: # bypass authentication for local networks
    #     - 10.0.0.0/8
    #     - 192.168.0.0/16
    #     - 172.16.0.0/12
    - domain:
        - "*.kemeel.com"
        - "kemeel.com"
      policy: two_factor

# https://www.authelia.com/configuration/session/introduction/
session:
  name: authelia_session
  same_site: lax
  expiration: 7h
  inactivity: 5m
  remember_me: 1M
  cookies:
    - domain: 'kemeel.com'
      authelia_url: 'https://authelia.kemeel.com'
      default_redirection_url: 'https://kemeel.com'
  # AUTHELIA_REDIS_PLACEHOLDER

# https://www.authelia.com/configuration/security/regulation/
regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

# https://www.authelia.com/configuration/storage/introduction/
storage:
  # For local storage, uncomment lines below and comment out mysql. https://docs.authelia.com/configuration/storage/sqlite.html
  # This is good for the beginning. If you have a busy site then switch to other databases.
  local:
   path: /config/db.sqlite3

# https://www.authelia.com/configuration/notifications/introduction/
notifier:
  disable_startup_check: false
  # For testing purposes, notifications can be sent in a file. Be sure to map the volume in docker-compose.
  filesystem:
    filename: /config/notifications.txt

##
## Identity Providers
##
identity_providers:

  ##
  ## OpenID Connect (Identity Provider)
  ##
  ## It's recommended you read the documentation before configuration of this section:
  ## https://www.authelia.com/c/oidc
  oidc:
    ## The hmac_secret is used to sign OAuth2 tokens (authorization code, access tokens and refresh tokens).
    ## HMAC Secret can also be set using a secret: https://www.authelia.com/c/secrets
    hmac_secret: 3c58985dd829b3dde7c3d3f60d6ab3188ac191cfba700441aabd643c5ba8dcc1

    ## The issuer_certificate_chain is an optional PEM encoded certificate chain. It's used in conjunction with the
    ## issuer_private_key to sign JWT's. All certificates in the chain must be within the validity period, and every
    ## certificate included must be signed by the certificate immediately after it if provided.
    issuer_certificate_chain: |
      -----BEGIN CERTIFICATE-----
     MIIDCzCCAfOgAwIBAgIUFvwkiGxdG4I+UPQ94CNetEL/pZQwDQYJKoZIhvcNAQEL
     BQAwFTETMBEGA1UEAwwKa2VtZWVsLmNvbTAeFw0yNTEwMjEwNzI3MTFaFw0yNjEw
     MjEwNzI3MTFaMBUxEzARBgNVBAMMCmtlbWVlbC5jb20wggEiMA0GCSqGSIb3DQEB
     AQUAA4IBDwAwggEKAoIBAQCr0YC5dTDFK3geMio05ZM3nKLsYtJpSRcqw5R4RsMR
     MBGNbccNNE6VrxkQy1K1fYdZ+PhZDho+vLjc8Sn/gWEnAh0vcXUmyI+7nc0U6+F9
     ZubJKAZVUDrbV4wR8zYxdgl4btKBa6YqT/eMXeQDRA/gGEQivhxqkcSInw5Dq5Mp
     Bqv6L0/ma2mFXmQp8PULX0C9f20jH658dtkeoH/9Pibu+siOuL2qt2yhqi5CIqsK
     JwI53wNlBhwQDdV58bofRjAAS4b64gn70A6k230Oba19ja5WT1WXyB+/PSG5IkQx
     rdEFw3Z0d0V0yF+Tdevr0b+hW71x1IPN4iVP6BfxkdSlAgMBAAGjUzBRMB0GA1Ud
     DgQWBBSZq50s1RHtX9Sd5aToZuiTjCL35jAfBgNVHSMEGDAWgBSZq50s1RHtX9Sd
     5aToZuiTjCL35jAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBu
     xzfhM+C/wnIOH/G7Q2PKmtB+dEOLT/PDZYyAvd5UTYsu/1PWSRFNFClmqn/J5vHq
     nDhoPodu8r+1CmvsmVUxWYrPO4AJcUuoXhsPJCxtxYNNuAv/9BNziZRvMJWbzmYl
     6FuYeCWaqiAfl6lIAR2+iUvv4GD868+ScZLB21hioLgwl36feAle3NQrgecEXgeI
     350f2s6H2TXfE7Bq6xNbd9p+4DZ37h0lb+dCb1Syr3l+cdzwbL3++7KOfQIYSUlX
     x6LBz0gRV1CqQ6tXelb51MWuUufoCbJZPkfsPTyV1dYxZSI1TyoPqY252UO45GfT
     jxdAl0Go0Gm/tDS4bipI
     -----END CERTIFICATE-----
    ## The issuer_private_key is used to sign the JWT forged by OpenID Connect.
    ## Issuer Private Key can also be set using a secret: https://www.authelia.com/c/secrets
    issuer_private_key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCr0YC5dTDFK3ge
      Mio05ZM3nKLsYtJpSRcqw5R4RsMRMBGNbccNNE6VrxkQy1K1fYdZ+PhZDho+vLjc
      8Sn/gWEnAh0vcXUmyI+7nc0U6+F9ZubJKAZVUDrbV4wR8zYxdgl4btKBa6YqT/eM
      XeQDRA/gGEQivhxqkcSInw5Dq5MpBqv6L0/ma2mFXmQp8PULX0C9f20jH658dtke
      oH/9Pibu+siOuL2qt2yhqi5CIqsKJwI53wNlBhwQDdV58bofRjAAS4b64gn70A6k
      230Oba19ja5WT1WXyB+/PSG5IkQxrdEFw3Z0d0V0yF+Tdevr0b+hW71x1IPN4iVP
      6BfxkdSlAgMBAAECggEAAreEqRB7OnFTBdGcpqR6ScO7NP1+pUKOHSBL/Z2xob8+
      vJusef8TPqOu3XvRk+Qajhr1PMQP0mEkLTFoQBpY7m4TbXe5g5wu30EbocXCSLwM
      g/uTI6mdAwqx2mpo0RE0QIhdrl7RsrnIyM2G3vq/1rcB6mi5XoGg99lIBClQ4bIR
      XMnUKgSbRYNMf5hwwgjBzvjw7A9yyxb1wsJLmJAQQ/j6wF2z5cNxz2MdFqqjTZ0f
      ogHK1k2bl39P2vny9mVMiZBb3AOav0lQzHaVEwTf6EM1bZCyLDb/ZaN38oTUZGJ7
      rPSb+TtaqcKKCyXfNbo4jWQCO88Nj/cwT2pSOJ+5kQKBgQDhRtfvyUYmftt2GLQ/
      r8YINrDPeXPjbRcFMDzlcaHqJJS1IU+KONCmvvxesQmAFVWLlUCbIfEMSd490nRg
      UuLabYPGL36/DkSDDu+DyOjrz8z67vWv0r51Ehr6OngqMrt8iheagcHyUkYR4OlD
      D987VLluL2nU0nEtLRahvQ38/QKBgQDDQEA9fjZCoBlYapRLBDgmrvywVo1FeuT9
      oConr31NTuVdrJap+sWaYArMx7xEKmSb/KFcWy57h1CuiEnPZkyGZW0PxwyLWzZM
      RsCiibynT6dug0JLJ8i4CCYV6L75HL6vblXVz78PH4tFGpiHELS21uIWY1/L57co
      QcnRxN6ayQKBgQCbdbIKjZFVe3Gje8TXtkso2+UEKEIrDds2/2TmyZX86KWeoZAs
      SKzkhSPPjMiLlS1ll+fvpmqcGlW9wAADgO9/4Ndw6tHCsuvgrWvoO7tRECPafxEY
      9ovsakQnrjXCmSP8+6byPt1ChjhImjceylM4tG0KdrnH3jmv/U+C6d4/WQKBgGi8
      R3l1AYA9xzrBeSjAa6p8hXnGA+P4Z2uRheth3JIitzDHis5Fgcgsqr5sihX6s5tl
      Kd2T39xNmr70xrslQfl54MXs3VLHq9nAvkayIeuR89t5N49/GNF3NY7dGcwhWjxa
      sFqQJQnkvt1jxdv13yqRHBgsWE/VzU8f8zW+KDbZAoGBAIrrrtrAww7XI9chjfKi
      KxgtKHkAw5DWB8BF2ri45CFkeXCkyaPHGt6VOdARwSRp6g+UkPQ16cynO14XBeiP
      0z3Hz0UR2Gg1KDeFVR4SWe+BJ8nvJcpE+FCOW2p9xZ/yu8RS6fLLoMzvcBjn/sa2
      4KIPFIEG3oe8C3GgIBRGuI5k
      -----END PRIVATE KEY-----
      
    ## The lifespans configure the expiration for these token types.
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m

    ## Enables additional debug messages.
    enable_client_debug_messages: false

    ## SECURITY NOTICE: It's not recommended changing this option and values below 8 are strongly discouraged.
    minimum_parameter_entropy: 8

    ## SECURITY NOTICE: It's not recommended changing this option, and highly discouraged to have it set to 'never'
    ## for security reasons.
    enforce_pkce: public_clients_only

    ## Cross-Origin Resource Sharing (CORS) settings.
    cors:
      ## List of endpoints in addition to the metadata endpoints to permit cross-origin requests on.
      endpoints:
         - authorization
         - token
         - revocation
         - introspection
         - userinfo

      ## List of allowed origins.
      ## Any origin with https is permitted unless this option is configured or the
      ## allowed_origins_from_client_redirect_uris option is enabled.
      allowed_origins:
        - https://kemeel.com

      ## Automatically adds the origin portion of all redirect URI's on all clients to the list of allowed_origins,
      ## provided they have the scheme http or https and do not have the hostname of localhost.
      allowed_origins_from_client_redirect_uris: false

    ## Clients is a list of known clients and their configuration.
    # clients:
      # -
        ## The ID is the OpenID Connect ClientID which is used to link an application to a configuration.
        # id: myapp

        ## The description to show to users when they end up on the consent screen. Defaults to the ID above.
        # description: My Application

        ## The client secret is a shared secret between Authelia and the consumer of this client.
        # secret: this_is_a_secret

        ## Sector Identifiers are occasionally used to generate pairwise subject identifiers. In most cases this is not
        ## necessary. Read the documentation for more information.
        ## The subject identifier must be the host component of a URL, which is a domain name with an optional port.
        # sector_identifier: example.com

        ## Sets the client to public. This should typically not be set, please see the documentation for usage.
        # public: false

        ## The policy to require for this client; one_factor or two_factor.
        # authorization_policy: two_factor

        ## The consent mode controls how consent is obtained.
        # consent_mode: auto

        ## This value controls the duration a consent on this client remains remembered when the consent mode is
        ## configured as 'auto' or 'pre-configured'.
        # pre_configured_consent_duration: 1w

        ## Audience this client is allowed to request.
        # audience: []

        ## Scopes this client is allowed to request.
        # scopes:
          # - openid
          # - groups
          # - email
          # - profile

        ## Redirect URI's specifies a list of valid case-sensitive callbacks for this client.
        # redirect_uris:
        # - https://oidc.example.com:8080/oauth2/callback

        ## Grant Types configures which grants this client can obtain.
        ## It's not recommended to define this unless you know what you're doing.
        # grant_types:
          # - refresh_token
          # - authorization_code

        ## Response Types configures which responses this client can be sent.
        ## It's not recommended to define this unless you know what you're doing.
        # response_types:
          # - code

        ## Response Modes configures which response modes this client supports.
        # response_modes:
          # - form_post
          # - query
          # - fragment

        ## The algorithm used to sign userinfo endpoint responses for this client, either none or RS256.
        # userinfo_signing_algorithm: none


   
