http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.0.0.0/24
    - 192.168.14.0/24
    - 192.168.15.0/24
    - 192.168.5.0/24

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Google Assistant #disable firewall robots cloudflare to link to google home
google_assistant:
  project_id: grogu-472219
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true
  expose_by_default: true

notify:
  - platform: telegram
    name: grogu
    chat_id: -1001410345629
