name: deploy grogu-hs stack

on:
  push:
    branches:
      - main
  workflow_dispatch:   # this enables the "Run workflow" button in GitHub

jobs:
  deploy:
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: /home/medivh/docker
    steps:    
      - name: Sync repo into /home/medivh/docker
        run: |
          if [ ! -d "/home/medivh/docker/.git" ]; then
            git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/esculato/Grogu.git
          else
            git fetch origin main
            git reset --hard origin/main
          fi

      - name: Redeploy stack
        run: |
          docker compose -f docker-compose-hs.yml pull
          docker compose -f docker-compose-hs.yml up -d
